// Define action type constants
export const UPDATE_ALERT_METHOD = 'UPDATE_ALERT_METHOD';
export const UPDATE_ALERT_TYPE = 'UPDATE_ALERT_TYPE';
export const UPDATE_INTEREST_RATE = 'UPDATE_INTEREST_RATE';
export const UPDATE_FREQUENCY = 'UPDATE_FREQUENCY';
export const ADD_ALERT = 'ADD_ALERT';
export const ALERT_OFF = 'ALERT_OFF';
export const UPDATE_ALERT = 'UPDATE_ALERT';
export const DELETE_ALERT = 'DELETE_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
