const IS_DEMO_MODE = process.env.REACT_APP_IS_DEMO_MODE === 'true';
const DEFAULT_PROTOCOL = process.env.REACT_APP_DEFAULT_PROTOCOL || "Compound Finance";

const COINBASE_CLIENT_SECRET = process.env.REACT_APP_COINBASE_CLIENT_SECRET;
const COINBASE_CLIENT_ID = process.env.REACT_APP_COINBASE_CLIENT_ID;
const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
const WITHDRAWAL_ADDRESS = process.env.REACT_APP_WITHDRAWAL_ADDRESS;

module.exports = {
    IS_DEMO_MODE,
    DEFAULT_PROTOCOL,
    COINBASE_CLIENT_SECRET, 
    COINBASE_CLIENT_ID,
    BACKEND_URL,
    WITHDRAWAL_ADDRESS,
}