swagger: "2.0"
info:
  title: Rocko API
  version: "0.0.7"
host: localhost:5000
basePath: "/"
schemes:
  - https
  - http
paths:
  /items:
    get:
      summary: List all items
      responses:
        200:
          description: An array of thingamabobs[]
          schema:
            type: array
            items:
              $ref: '#/definitions/Item'
definitions:
  Item:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
