CREATE TABLE `asset_data_base_compound` (
  `id` int NOT NULL AUTO_INCREMENT,
  `fetch_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lending_protocol` varchar(15) DEFAULT NULL,
  `protocol_version` varchar(5) DEFAULT NULL,
  `network` varchar(10) DEFAULT NULL,
  `loan_asset` varchar(10) DEFAULT NULL,
  `base_price` double DEFAULT '0',
  `comp_price` double DEFAULT '0',
  `utilization` double DEFAULT '0',
  `utilization_percent` double DEFAULT '0',
  `available` double DEFAULT '0',
  `supply_rate` double DEFAULT '0',
  `supply_apr` double DEFAULT '0',
  `supply_total` double DEFAULT '0',
  `comp_to_suppliers_per_day` double DEFAULT '0',
  `supply_reward_rate` double DEFAULT '0',
  `supply_net_rate` double DEFAULT '0',
  `borrow_rate` double DEFAULT '0',
  `borrow_apr` double DEFAULT '0',
  `borrow_total` double DEFAULT '0',
  `borrow_collateral_factor` double DEFAULT NULL,
  `comp_to_borrowers_per_day` double DEFAULT '0',
  `borrow_reward_rate` double DEFAULT '0',
  `borrow_net_rate` double DEFAULT '0',
  `borrow_min` double DEFAULT '0',
  `borrow_reward_min` double DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `fetch_time` (`fetch_time`)
)