ALTER TABLE daily_metrics MODIFY COLUMN total_outstanding_balance DECIMAL(20,6) DEFAULT '0.00';

ALTER TABLE transactions MODIFY COLUMN usd_value DECIMAL(20,6) DEFAULT '0.00';
ALTER TABLE transactions MODIFY COLUMN amount BIGINT UNSIGNED DEFAULT 0;

ALTER TABLE loans MODIFY COLUMN principal_balance DECIMAL(20,6) DEFAULT '0.00';
ALTER TABLE loans MODIFY COLUMN outstanding_balance DECIMAL(20,6) DEFAULT '0.00';
ALTER TABLE loans MODIFY COLUMN interest DECIMAL(20,6) DEFAULT '0.00';

ALTER TABLE loans ADD COLUMN collateral_asset ENUM('eth', 'comp', 'link', 'uni', 'wbtc');
ALTER TABLE loans ADD COLUMN collateral_decimals TINYINT UNSIGNED DEFAULT 0;
ALTER TABLE loans MODIFY COLUMN collateral BIGINT UNSIGNED DEFAULT 0;
