variable "domain" {}
variable "environment" {}
variable "subdomain" {}
variable "region" {}
variable "vpc_cidr_block" {}
variable "vpc_public_subnet1_cidr_block" {}
variable "vpc_public_subnet2_cidr_block" {}
variable "vpc_private_subnet1_cidr_block" {}
variable "vpc_private_subnet2_cidr_block" {}
variable "vpc_public_subnet1_az" {}
variable "vpc_public_subnet2_az" {}
variable "vpc_private_subnet1_az" {}
variable "vpc_private_subnet2_az" {}
variable "vpc_flow_logs_s3_bucket" {}
