name: Backend Build and Deploy

on:
  push:
    branches: [develop]

jobs:
  build_and_deploy:
    environment: dev
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build server
      working-directory: ./server
      run: |
       ./docker_build.sh
       ./docker_push.sh dev
       ./docker_deploy.sh dev

