name: Backend Build and Deploy

on:
  push:
    branches: [develop]

jobs:
  build_and_deploy:
    environment: dev
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build server
      working-directory: ./server
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
        AWS_DEFAULT_OUTPUT: json
      run: |
       ./docker_build.sh
       ./docker_push.sh dev
       ./docker_deploy.sh dev

